/**
 * services/projectService.js
 *
 * Single entry point for reading projects. Callers never need to know
 * whether the database is up.
 *
 *   DB reachable and holding projects -> read from MongoDB
 *   otherwise                          -> read bundled seed data
 *
 * The fallback is not an error state. A visitor must always see the projects,
 * so every failure path resolves to the seed list rather than throwing.
 */

const Project = require('../models/Project');
const seedProjects = require('../data/projects');
// Read at call time (not destructured) so tests can swap isDbReady.
const db = require('../config/db');

/** Splits an already-ordered list into its featured and remaining halves. */
function partition(list) {
  return {
    featured: list.filter((p) => p.featured),
    others: list.filter((p) => !p.featured),
  };
}

/** Sorts a plain list the same way the database query does. */
function byDisplayOrder(a, b) {
  if (a.featured !== b.featured) return a.featured ? -1 : 1;
  return (a.order || 0) - (b.order || 0);
}

/**
 * Applies the defaults the schema would normally supply, so offline data and
 * database documents are shaped identically for the view layer.
 */
function withDefaults(project) {
  return {
    title: '',
    shortDescription: '',
    description: '',
    problem: '',
    solution: '',
    features: [],
    technologies: [],
    category: 'Other',
    tags: [],
    year: null,
    image: '',
    imageAlt: '',
    placeholderIcon: 'code',
    githubUrl: '',
    liveUrl: '',
    featured: false,
    order: 0,
    ...project,
    // Database documents already carry a slug. Seed objects do not, because the
    // slug is generated by a Mongoose hook that only runs on save — so it has to
    // be derived here too, or every card would render the same empty id.
    slug: project.slug || Project.slugify(project.title),
    // An empty alt would make a screenshot unlabelled, so fall back to the
    // title rather than rendering alt="".
    imageAlt: project.imageAlt || project.title,
  };
}

/** The bundled content, normalised and ordered. */
function fromSeed() {
  const list = seedProjects.map(withDefaults).sort(byDisplayOrder);

  // Card ids come from slugs, so duplicates would produce duplicate ids in the
  // HTML. Resolved here because uniqueness needs the whole list in view.
  const seen = new Set();
  for (const project of list) {
    const base = project.slug || 'project';
    let slug = base;
    let suffix = 1;
    while (seen.has(slug)) {
      suffix += 1;
      slug = `${base}-${suffix}`;
    }
    project.slug = slug;
    seen.add(slug);
  }

  const { featured, others } = partition(list);
  return { featured, others, source: 'seed' };
}

/**
 * Resolves the projects to render.
 * Resolves to `{ featured, others, source }` and never rejects.
 */
async function getProjects() {
  if (!db.isDbReady()) return fromSeed();

  try {
    const docs = await Project.find()
      .sort({ featured: -1, order: 1 })
      .lean()
      .exec();

    // A reachable but empty collection falls back too: an empty Projects
    // section is worse than the bundled content.
    if (!docs.length) {
      console.warn('[projects] Collection is empty — serving bundled seed data.');
      return fromSeed();
    }

    const { featured, others } = partition(docs.map(withDefaults));
    return { featured, others, source: 'database' };
  } catch (error) {
    console.error('[projects] Read failed, serving bundled seed data:', error.message);
    return fromSeed();
  }
}

/**
 * Resolves a single project by slug for a public detail page.
 *
 * Like getProjects, this serves readers — a visitor who reached a project via
 * a card must always see that project. Database-first; a miss or a failed read
 * falls back to the bundled seed (which is what the index page would have
 * shown for the same moment), so the detail page can never contradict the
 * list that linked to it.
 */
async function getBySlug(slug) {
  const key = String(slug || '');
  if (!key) return null;

  if (db.isDbReady()) {
    try {
      const doc = await Project.findOne({ slug: key }).exec();
      if (doc) return withDefaults(doc);
    } catch (error) {
      console.error('[projects] Detail read failed, trying bundled seed:', error.message);
    }
  }

  const { featured, others } = fromSeed();
  return [...featured, ...others].find((project) => project.slug === key) || null;
}

module.exports = { getProjects, getBySlug, fromSeed, partition, byDisplayOrder, withDefaults };
